### ISSUE TITLE
Mejorar plantillas de hbs, diseño botones, bug textarea 

### ISSUE THREAD

**Issue by WilberthGamboa** [WilberthGamboa/PcShareNest#18]
@ArielFdz 
# Tareas
1. Implementar la reutilización de html con hbs
2. El textarea de html por lo que veo no acepta el value por defecto, revisar implementación
3. Los inputs al parecer son muy cortos, al momento de editar, el valor que tenía el registro no alcanza en el input.

**Comment by ArielFdz** [comment]
Se completan los issues
